package com.collab.api.room.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;
import java.util.UUID;

/**
 * A collaborative editing room that maps 1-to-1 with a Yjs document on the
 * sync-server side.
 *
 * <p><b>Unclaimed rooms</b> ({@code ownerId == null}) are created by guests via
 * the quickshare flow. They expire after 24 hours unless claimed by a Member.
 *
 * <p><b>Claimed rooms</b> ({@code ownerId != null}) belong to a registered user
 * and persist permanently.
 *
 * <p>The {@code ownerId} stores a plain FK instead of a {@code @ManyToOne}
 * association so that loading a Room never triggers an implicit join to the
 * users table.
 */
@Entity
@Table(name = "rooms")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Room {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    /**
     * Short, human-friendly URL segment generated by the server (e.g. {@code "aB3dEf7g"}).
     * Unique across all rooms. Clients navigate to {@code /room/<slug>}.
     */
    @Column(nullable = false, unique = true)
    private String slug;

    /**
     * FK to the user who owns this room.
     * {@code null} for unclaimed rooms created by guests via the quickshare flow.
     */
    @Column(nullable = true)
    private UUID ownerId;

    /**
     * One-time opaque token that proves the presenter was the browser session
     * that created this room.
     *
     * <p>Generated at quickshare time for guest-created rooms; {@code null} for
     * rooms created by authenticated members (they are claimed immediately).
     * Cleared to {@code null} after a successful claim — single-use only.
     */
    @Column(nullable = true)
    private String creatorSecret;

    /**
     * Determines who can access and edit this room.
     * Defaults to {@link AccessMode#PUBLIC_EDIT} for quickshare rooms.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private AccessMode accessMode = AccessMode.PUBLIC_EDIT;

    /**
     * When this unclaimed room should be automatically deleted.
     * {@code null} for claimed (permanent) rooms.
     */
    @Column(nullable = true)
    private Instant expiresAt;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private Instant createdAt;
}
